<?xml version="1.0" ?>
<testsuite errors="0" failures="1" name="dataox.datasets.vacancies.tests.LocationTestCase" tests="1" time="0.323">
	<testcase classname="dataox.datasets.vacancies.tests.LocationTestCase" name="testSimple" time="0.323">
		<failure message="[] != None : 'Bodleian Libraries Directorate, Clarendon Building, Oxford' &gt; [] != []" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/alex/Projects/dataox/dataox/datasets/vacancies/tests.py", line 46, in testSimple
    map(guesser.get_names, expected or [])))
AssertionError: [] != None : 'Bodleian Libraries Directorate, Clarendon Building, Oxford' > [] != []
]]>		</failure>
	</testcase>
	<system-out/>
	<system-err/>
</testsuite>
